### ISSUE TITLE
Improve readme

### ISSUE THREAD

**Issue by mezotv** [mezotv/hello-world#2]
The current readme is a bit ugly because i made it in like 5minutes. With a bit more time it could look better for future contributors.

**Comment by InsightCracker** [comment]
Can you please assign this to me

**Comment by mezotv** [comment]
> Can you please assign this to me

Sure will do!

**Comment by InsightCracker** [comment]
Thanks..

I'll make a PR soon

**Comment by sumitbaroniya** [comment]
please assign me this issue.

**Comment by InsightCracker** [comment]
I was about to make a pull request when you close the issue. But no problem.
you can check my pull request on the changes I made to the typescript code.
